### ISSUE TITLE
您好，大神

### ISSUE THREAD

**Issue by zkailinzhang** [Stev00/wechat_vote#1]
我在readme中看到，“”一个人可多次投票，间隔5分钟左右“”，我想问下，我这有个微信投票网址，也是第三方网站，但是要绑定微信账号才能投票，并且一个账号只能投一次，，那这个也能通过程序 做到一个微信账号投多次吗

**Comment by Stev00** [comment]
一个帐号只能投一次的话这个方法就不能直接用了，问题在于你怎样弄出他们服务器认为合法的openid。服务器如果没有openid验证的话，你就随机生成吧，然后用这个框架去刷；有openid验证的话这方法行不通。

**Comment by gdoudeng** [comment]
> 我在readme中看到，“”一个人可多次投票，间隔5分钟左右“”，我想问下，我这有个微信投票网址，也是第三方网站，但是要绑定微信账号才能投票，并且一个账号只能投一次，，那这个也能通过程序 做到一个微信账号投多次吗

@zkailinzhang 老哥你咋解决的
